package org.piperiverstudios.dhall.plugin.dhall

import com.intellij.psi.tree.TokenSet
import org.piperiverstudios.dhall.plugin.dhall.psi.DhallTypes

object DhallTokens {

  val COMMENTS: TokenSet = TokenSet.create(DhallTypes.COMMENT)
  val KEYWORDS           = TokenSet.create(DhallTypes.IF, DhallTypes.THEN)

  val IF: TokenSet               = TokenSet.create(DhallTypes.IF)
  val THEN: TokenSet             = TokenSet.create(DhallTypes.THEN)
  val ELSE: TokenSet             = TokenSet.create(DhallTypes.ELSE)
  val LET: TokenSet              = TokenSet.create(DhallTypes.LET)
  val IN: TokenSet               = TokenSet.create(DhallTypes.IN)
  val AS: TokenSet               = TokenSet.create(DhallTypes.AS)
  val USING: TokenSet            = TokenSet.create(DhallTypes.USING)
  val MERGE: TokenSet            = TokenSet.create(DhallTypes.MERGE)
  val MISSING: TokenSet          = TokenSet.create(DhallTypes.MISSING)
  val INFINITY: TokenSet         = TokenSet.create(DhallTypes.INFINITY)
  val NAN: TokenSet              = TokenSet.create(DhallTypes.NAN)
  val SOME: TokenSet             = TokenSet.create(DhallTypes.SOME)
  val TO_MAP: TokenSet           = TokenSet.create(DhallTypes.TO_MAP)
  val ASSERT: TokenSet           = TokenSet.create(DhallTypes.ASSERT)
  val FORALL: TokenSet           = TokenSet.create(DhallTypes.FORALL)
  val WITH: TokenSet             = TokenSet.create(DhallTypes.WITH)
  val SHOW_CONSTRUCTOR: TokenSet = TokenSet.create(DhallTypes.SHOW_CONSTRUCTOR)
  val BOOL: TokenSet             = TokenSet.create(DhallTypes.BOOL)
  val TRUE: TokenSet             = TokenSet.create(DhallTypes.TRUE)
  val FALSE: TokenSet            = TokenSet.create(DhallTypes.FALSE)
  val OPTIONAL: TokenSet         = TokenSet.create(DhallTypes.OPTIONAL)
  val NONE: TokenSet             = TokenSet.create(DhallTypes.NONE)
  val NATURAL: TokenSet          = TokenSet.create(DhallTypes.NATURAL)
  val INTEGER: TokenSet          = TokenSet.create(DhallTypes.INTEGER)
  val DOUBLE: TokenSet           = TokenSet.create(DhallTypes.DOUBLE)
  val TEXT: TokenSet             = TokenSet.create(DhallTypes.TEXT)
  val BYTES: TokenSet            = TokenSet.create(DhallTypes.BYTES)
  val DATE: TokenSet             = TokenSet.create(DhallTypes.DATE)
  val TIMEZONE: TokenSet         = TokenSet.create(DhallTypes.TIMEZONE)
  val TIME: TokenSet             = TokenSet.create(DhallTypes.TIME)
  val LIST: TokenSet             = TokenSet.create(DhallTypes.LIST)
  val TYPE: TokenSet             = TokenSet.create(DhallTypes.TYPE)
  val KIND: TokenSet             = TokenSet.create(DhallTypes.KIND)
  val SORT: TokenSet             = TokenSet.create(DhallTypes.SORT)
  val IDENTIFIER: TokenSet       = TokenSet.create(DhallTypes.IDENTIFIER)
  val COMMENT: TokenSet          = TokenSet.create(DhallTypes.COMMENT)
  val COMBINE: TokenSet          = TokenSet.create(DhallTypes.COMBINE)
  val COMBINE_TYPES: TokenSet    = TokenSet.create(DhallTypes.COMBINE_TYPES)
  val EQUIVALENT: TokenSet       = TokenSet.create(DhallTypes.EQUIVALENT)
  val PREFER: TokenSet           = TokenSet.create(DhallTypes.PREFER)
  val LAMBDA: TokenSet           = TokenSet.create(DhallTypes.LAMBDA)
  val ARROW: TokenSet            = TokenSet.create(DhallTypes.ARROW)
  val COMPLETE: TokenSet         = TokenSet.create(DhallTypes.COMPLETE)
  val COLON: TokenSet            = TokenSet.create(DhallTypes.COLON)
  val EQEQ: TokenSet             = TokenSet.create(DhallTypes.EQEQ)
  val EQ: TokenSet               = TokenSet.create(DhallTypes.EQ)
  val PLUS: TokenSet             = TokenSet.create(DhallTypes.PLUS)
  val MINUS: TokenSet            = TokenSet.create(DhallTypes.MINUS)
  val GREATER: TokenSet          = TokenSet.create(DhallTypes.GREATER)
  val SMALLER: TokenSet          = TokenSet.create(DhallTypes.SMALLER)
  val GREATER_EQ: TokenSet       = TokenSet.create(DhallTypes.GREATER_EQ)
  val SMALLER_EQ: TokenSet       = TokenSet.create(DhallTypes.SMALLER_EQ)
  val STRING: TokenSet           = TokenSet.create(DhallTypes.STRING)
  val NUMBER_INT: TokenSet       = TokenSet.create(DhallTypes.NUMBER_INT)
  val NUMBER_FP: TokenSet        = TokenSet.create(DhallTypes.NUMBER_FP)

}
